### PR TITLE
Add new theme to search page and improve cross-linking

### PR DESCRIPTION
**Pull request by fatlotus**
Because I think the current design feels a little plain, I've tweaked things a bit to give it a more organic feel ("a rummage sale with prices, labels, and a massive hogepoge of images"). It might be a little overwhelming, though — @tbkissinger, thoughts? 

Old version: https;//hosted-caravel.appspot.com
Proposed change: https://make-more-hipstery-dot-hosted-caravel.appspot.com

### CODE REVIEW

**Comment by georgeteo** [comment]
I like the old one better (have second opinion from random person). It looks cleaner and more professional; this one looks like a website from the 00s. I don't mind keeping the nav bar header but I think the thumbnails should look like the old one.

**Comment by fatlotus** [comment]
Naturally, I disagree :) I think we can find something we're both happy with, though. To be honest, I'm not happy with the listing view here, either, but I don't want the site to look like a Bootstrap template, and I think the old version wasted vertical space on Desktop.

Compromise for listing view: keep prices listed as a tag, display titles underneath. Thoughts?

**Comment by georgeteo** [comment]
Compromise of the compromise: keep prices listed as tag, display title underneath and have some sort of thumbnail to contain it. Just having pictures seems a bit rough. 

Also rounded corners do not seem terrible. Many sites have rounded corners these days. See pintrest.

**Comment by fatlotus** [comment]
Okay! Price tags, title underneath, with a round background thingy. So, like Pinterest, there's no margin above the photo with white space, only below. If we're going that way, we might want shadows. (I'm neutral.) Thoughts?

**Comment by georgeteo** [comment]
Am neutral about shadows too. Am thinking we try a flat design first and fix it if something is wrong. Hard to say before seeing it.

**Comment by fatlotus** [comment]
Added flat, bendy version, as we talked about on FB earlier. It can be poked at the same URL as before.

**Comment by georgeteo** [comment]
Am not feeling it. 

Other suggestions:
1. Change the green tag to the same color as the UChicago logo, which will exist in the new nav bar?
2. Center text
3. Change font to match my header font: Josefin Sans:
CSS: font-family: 'Josefin Sans', sans-serif;
Reference: <link href='http://fonts.googleapis.com/css?family=Josefin+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

**Comment by fatlotus** [comment]
I've changed the color from green to red, and centered the text. Still want me to use Josefin Sans? It seems a little strong for us.

**Comment by georgeteo** [comment]
I am thinking a less bold/thick font. But like the dropdown inquiry listings page, we could table the issue for now. Will merge.

**Pull request merged**
