### PR TITLE
Session handling

### PR DESCRIPTION
**Pull request by georgeteo**
Wohoo basic session handling. Sorry it took so long. 

Need to implement the email verification functionality, but I figured we should get the regular email feature up first then piggy back on that to send the confirmation/verification emails.

### CODE REVIEW

**Comment by fatlotus** [comment]
Fun fact: if you use branches without underscores (session-handling, instead of session_handling), they will automatically get a test instance on GAE (https://session-handling-dot-latest-dot-hosted-caravel.appspot.com, in this case).

**Comment by fatlotus** [comment]
I'm not sure we want to have an explicit login/logout feature. The main benefit of having no passwords is instant gratification; so I think it's a business requirement that people should be able to create (but not "publish") listings without going to their email. Here's what I'm imagining:

**Buying Something (not logged in)**:
Student goes to site, views listings. If they visit one, there is a "Place Inquiry" form that looks like the following:

    Your Email: [    ] (@uchicago.edu preferred)
    Body:       [          ]
    <place inquiry>

**Buying Something (logged in)**:
As above, but:

    Your Email: myemailaddress@uchicago.edu
    Body:       [          ]
    <place inquiry>

**Selling something (not logged in)**:
(1) They go to the "post listing" form, and see:

    Listing Title: [    ]
    Your Email:    [    ] (@uchicago.edu required)
    Body:          [        ]
    <post listing>

(2) Upon clicking "submit," they are redirected to the home page. That listing is only visible to them (there's a big red banner telling them that) until they open the link they have just received via email:

    Hi Bob!
        
    Click the link below to publish your listing on Marketplace:
    https://marketplace/validate?key=BLAHBLAH

(3) Upon clicking the link, the student is marked logged in, and is redirected to the listing.

**Selling something (logged in)**:
(1) They go to the "post listing" form, and see:

    Listing Title: [    ]
    Your Email:    myemailaddress@uchicago.edu
    Body:          [        ]
    <post listing>

(2) Upon clicking the link, the user is redirected to the listing.

**Editing a listing (logged in, on a listing they can edit)***:
(1) The page contains a link to an edit form ("Edit this listing"):

    Listing Title: [    ]
    Body:          [        ]
    <update>

**Editing a listing (not logged in)***:
(1) The page contains a link to a login form ("This is my listing"):

    Your email: [    ] (@uchicago.edu required)
    <re-send admin link>

(2) They receive the same email as in the unauthenticated Post Listing flow.

**Editing a listing (different email)***:
(1) We show nothing on the page. (Ideally nobody will have two accounts :/)

Thoughts?

**Comment by georgeteo** [comment]
Hey Jeremy. I did up my interpretation of the features. Could you take a look at it to see if that is what you had in mind? 

There is some commented out code in main.py (under the /new route) which is suppose to ensure the header is handled correctly, but it isn't working at the moment. 

Also, I am currently reinitializing the email_form and verification_form in every route to ensure that the header in each view renders correctly. This seems dumb. Any suggestions for making this better?

**Comment by fatlotus** [comment]
W.r.t what's we've currently got: I tried to run it, but am getting "UndefinedError: 'wtf' is undefined" in the templates (this is on https://session-handling-dot-hosted-caravel.appspot.com/dell-ultrasharp-1907fp-19-lcd-flat-panel-monitor); I ran `git pull && git reset --hard origin/session_handling` first, so this should be the latest version... is there something else I need to do here?

I'm still not convinced we need a separate login/logout/register flow (beyond the one implicit in placing a listing). Do you have a user story in mind?

In general, I think flask apps work best in the REST model, where each "action" (either getting something or setting something) corresponds to a specific (method, URL) tuple. I think if we stick to that, we won't have the same problems with duplicated code. Here's one way this could work:

    GET  /?q=cats                   # show a bunch of listings
    GET  /tim-the-cat               # show a specific listing
    GET  /tim-the-cat/edit          # show an edit form (action=/tim-the-cat)
    POST /tim-the-cat               # edit a specific listing
    GET  /tim-the-cat?key=XXXXXXXXX # login (redirects to /tim-the-cat)
    GET  /create                    # shows a creation form (action=/)
    POST /                          # creates a new listing

I'm realizing now it might be easier to do the unauthenticated "post listing" flow first (where anybody can post any listing). I'd be happy to help out — unfortunately, sessions touch a lot of this app. Thoughts?

**Comment by georgeteo** [comment]
Fixed the first bug. Sorry, forgot an import in one of the html files. 

Re. the REST model, does that mean my ajax login/logout doesn't jive with this model?

**Pull request closed without merging**
