### PR TITLE
About pages

### PR DESCRIPTION
**Pull request by georgeteo**
About and help pages. Hopefully this reduces the number of emails we get.

### CODE REVIEW

**Comment by fatlotus** [comment]
Er, is the "About" page accurate? I didn't think we did any expiration/renewal logic.

**Comment by georgeteo** [comment]
Oops. I was justing using the existing about page thats sitting in the templates directory. I assumed it's been updated since you've put our names on it. 

Will remove.

**Comment by georgeteo** [comment]
Fixed.

**Comment by fatlotus** [comment]
Looks good to me!

**Comment by georgeteo** [comment]
Fixes #132

**Pull request merged**
