### PR TITLE
adding new navbar based index page

### PR DESCRIPTION
**Pull request by georgeteo**
Extracted the navbar based UI change from rudimentary-session-handling to this branch. Content is identical.

### CODE REVIEW

**Comment by fatlotus** [comment]
Can you merge these changes on top of the new navbar? It looks like there's a merge conflict.

**Comment by fatlotus** [comment]
Ah, whoops, that was my bad. I meant "please rebase on this branch," rather than "please merge onto master" — haven't had a chance to read over this one.

**Comment by georgeteo** [comment]
I think this is the new nav bar, what would I rebase?

**Comment by fatlotus** [comment]
I mean, please revert the change to master, then patch merge conflicts (if they are still there), then fix the weird failing test thingies.

**Comment by georgeteo** [comment]
Fixed merge conflict, but am unsure about the ci error.

**Comment by fatlotus** [comment]
Oh, the CI failure is fine — it just doesn't like uppercase version names. It's fairly strict — it wants the branch name to match "^(?:^(?!-)[a-z\d\-]{0,62}[a-z\d]$)$," which roughly translates as "between 1 and 63 characters, not starting or ending with a dash."

**Pull request merged**
