### PR TITLE
Add live migration feature from production. 

### PR DESCRIPTION
**Pull request by fatlotus**
Since I'd like to get this going as soon as possible, I'd like to add this hook into our application so that we're tracking live data. Once deployed, I'm planning to add code akin to the following into the creation and edit routines in the live Rails app:

```ruby
require 'net/http'

# (later)
Net::HTTP.get("https://hosted-caravel.appspot.com/_pull?permalink=#{listing.permalink}")
```

### CODE REVIEW

**Comment by fatlotus** [comment]
By the way, please don't merge it yet — as written, this code will cause deadlocks (since Rails has bounded concurrency). I'm planning on having it enqueue a `deferred` task, which will reduce the likelihood of this happening.

**Comment by fatlotus** [comment]
Okay! Now we're good to go. Please take a look once you've got a chance.

Unfortunately, they've removed the freebie push-to-Deploy feature. There's a new one using Jenkins, but it costs money — about $0.002 per deployment. I'll investigate further, but in the interim, I'll just deploy whenever we merge a code review.

**Comment by georgeteo** [comment]
Looks good. 

One insignificant comment: can we change the "description" field in the state to "title" or something? Having description and detail is confusing to the first time reader.

**Comment by georgeteo** [comment]
Oops forgot to merge before commenting. 

Merged now.

**Comment by fatlotus** [comment]
(By the by, you don't have to merge something if it seems fishy to you — that's why we do code reviews.)

"Title" and "body," perhaps? "Name" and "details"?

**Comment by georgeteo** [comment]
Seemed like a trivial change that wont break things so I went ahead and merged it. Could always submit another pull request with the new names later. 

I vote title and body, but the other one sounds reasonable too. I'm fine with either.

**Comment by fatlotus** [comment]
Let's do "title" and "body." I'll prepare a pull request and add a migrator for the old entities.

**Pull request merged**
