### PR TITLE
Add image upload support

### PR DESCRIPTION
**Pull request by fatlotus**
See attached photo of UX:

screen shot 2015-10-03 at 4 39 40 pm

One potential problem is that this means any user can upload images to the site; I'm not sure what to do here.

### CODE REVIEW

**Comment by fatlotus** [comment]
There's a bug where the thumbnail_url is occasionally not set. Maybe just keep the same URL?

**Comment by georgeteo** [comment]
Why isn't the thumbnail url set?

**Comment by georgeteo** [comment]
bump my question?

**Comment by fatlotus** [comment]
Solution posted. Should be good to go.

**Comment by georgeteo** [comment]
Fix merge conflicts and merge away.

**Pull request merged**
