### PR TITLE
Rudimentary session handling

### PR DESCRIPTION
**Pull request by georgeteo**
I tried to make the commits be related to individual features. 

The last commit might be a bit large. Sorry about that. Hopefully it isn't too much to digest.

### CODE REVIEW

**Comment by georgeteo** [comment]
Okay. I've fixed up most of the comments from above. 

I've also added direct database writes for new/edit listings. I think think adding this controller should be on a different feature branch - if you agree, let me know. I'll revert and we can do it on another branch and abstracted as a nice packaged function.

**Comment by fatlotus** [comment]
1) I think you missed some. When replying, please comment "Fixed" on things that have been fixed. In particular, I'm confused why you're adding a styling changes in this CL.

2) Please do.

**Comment by georgeteo** [comment]
Okay. I have reverted the UI changes to the index and the direct write to database for new/edit listings from users who are already validated. Will add these in another branch. 

All other changes are fixed - except for comments which I am debating.

**Comment by fatlotus** [comment]
Ugh, still think the dropdowns are bad. That we can bikeshed later — but just for expediency I'm going to merge this now.

**Pull request merged**
