### PR TITLE
Prettifying Nav Bar

### LINKED ISSUE #65: Add SG logo to theme
I believe George was working on this, but I realize you've got stuff (so feel free to reassign). Looping in @tbkissinger for opinions on the mockup.

### PR DESCRIPTION
**Pull request by georgeteo**
Fixed #65.

Please do not merge yet. Am putting this pull request up to get your opinions @fatlotus @tbkissinger.

You can see the proposed changes at: https://ui-changes-lowercase-dot-hosted-caravel.appspot.com/.

- https://ui-changes-lowercase-dot-hosted-caravel.appspot.com/test-validated will show the version if the user session has a validated email.
- https://ui-changes-lowercase-dot-hosted-caravel.appspot.com/test-not-validated will show the version if the user session has an unvalidated email (so they haven't responded to an email, but have requested one). Jeremy: I am unsure whether this state should be recorded at this time. It seems like a reasonable feature to add so that users know which state they are in, but we could just have two states: (1) no email and not validated, and (2) email and validated.

Also, I am unsure that the Mange Listing and Logout buttons are clear. Will people know that they can click through to execute those actions?

**No email and not validated:**

screen shot 2015-09-18 at 8 24 32 am

**Yes email but not validated:**

screen shot 2015-09-18 at 8 25 06 am

**Yes email and validated:**

screen shot 2015-09-18 at 8 24 52 am

### CODE REVIEW

**Comment by fatlotus** [comment]
I think I agree that the "entered email but not validated" state is not particularly useful. Maybe just a binary state? That way, we don't need to use color to differentiate it. We could also make the email link to the "manage listings" view (which I still think of as a special case of a query).

In terms of overall look: generally looks good — is it possible to make the SG logo a bit smaller, and maybe move it down a tad? It feels higher than the centerline of the title text.

**Comment by georgeteo** [comment]
Okay take a look again. 

I have taken the binary state a bit further. Email only displayed if user logged in and validated. If not validated or no email registered to the session, nothing is displayed. I think this is clearer, because telling the user that "No email registered" might make it confusing (e.g., "how do i register/login?" questions). So username only displayed if the user can perform an action. 

I also moved it back to a dropdown menu because: 
1. functionally these actions are related to actions a user takes. 
2. looks cleaner.

**Comment by fatlotus** [comment]
Ah, good idea! That makes a lot of sense.

Again, I'm not sure a user "menu" really codifies an action. They can click it to go to a page with all their listings, but I don't think of that as doing something, per se — it certainly isn't changing state.

**Comment by fatlotus** [comment]
Eh whatever looks good to me. Resolve and merge?

**Comment by georgeteo** [comment]
Resolved. Merge away.

**Pull request merged**
