### PR TITLE
Lighten Roboto from 900 to 400

### PR DESCRIPTION
**Pull request by fatlotus**
Played around with it, and 400 seems the most "neutral." Thoughts?

(x-ref with #51)

### CODE REVIEW

**Comment by georgeteo** [comment]
I prefer 300. Thoughts?

**Comment by fatlotus** [comment]
I don't know if I want Marketplace to be "sleek" — 300 feels very Gap to me. Google Fonts has 400 as a "neutral" weight, which I think is a good balance of style and readability.

**Comment by georgeteo** [comment]
Okay. Will compromise.

**Comment by georgeteo** [comment]
Please merge.

**Comment by fatlotus** [comment]
shit i broke everything forgot about that. i will go fix

**Pull request merged**
