### PR TITLE
Add icons based on the category of a listing

### PR DESCRIPTION
**Pull request by fatlotus**
I added some color to each image, but generally, they're keeping to the same theme.

As shown, it's with the current theme. With the extra hipster sauce added, this looks like:

screen shot 2015-10-03 at 1 03 02 pm

### CODE REVIEW

**Comment by georgeteo** [comment]
Make the couple black images grey and remove the extra bike, then looks good.

**Comment by georgeteo** [comment]
bump change request?

**Comment by fatlotus** [comment]
Pushed! Thoughts?

**Comment by georgeteo** [comment]
Unsure about the bowtie guy. Is it distracting to have that be the only black one?

**Pull request merged**
