### PR TITLE
Add rudimentary unit tests

### PR DESCRIPTION
**Pull request by fatlotus**
It's fairly dumb, but:

```
Name                                   Stmts   Miss  Cover   Missing
--------------------------------------------------------------------
caravel.py                                14      0   100%   
caravel/controllers.py                     0      0   100%   
caravel/controllers/forms.py              49      5    90%   36-37, 49-50, 60
caravel/controllers/listings.py          166     71    57%   28, 41, 59, 95-96, 127-150, 157-212, 239, 242-243, 272-273, 287, 295-296, 300, 304
caravel/daemons.py                         0      0   100%   
caravel/daemons/delete_old_photos.py       5      2    60%   11-12
caravel/daemons/migration.py              10      6    40%   12-19
caravel/daemons/replication.py            32     24    25%   15-20, 27-78
caravel/policy.py                         12      2    83%   14-15
caravel/storage.py                         0      0   100%   
caravel/storage/cache.py                  66      1    98%   26
caravel/storage/config.py                 13      0   100%   
caravel/storage/dos.py                     9      0   100%   
caravel/storage/entities.py               95     14    85%   31-32, 63-64, 158-162, 169-170, 175, 180-181
caravel/storage/helpers.py                54      0   100%   
caravel/storage/photos.py                 52     41    21%   20-35, 42-70, 78-92
caravel/utils.py                          26      1    96%   16
--------------------------------------------------------------------
TOTAL                                    603    167    72%   
----------------------------------------------------------------------
Ran 12 tests in 0.841s

OK
```

### CODE REVIEW

**Comment by georgeteo** [comment]
So I've never used nosetests but should we consider changing framework? 

According to the docs, is no longer being maintained: 
https://nose.readthedocs.org/en/latest/

**Comment by fatlotus** [comment]
oh hrm

nose2, maybe?

**Comment by georgeteo** [comment]
Have no preference so defer to your judgement.

**Comment by fatlotus** [comment]
Bonk! Please take another look

**Pull request merged**
