### PR TITLE
fixing price in list view

### LINKED ISSUE #205: List View Offset Error
> When viewing items, looks as if there might be decimal issue with pricing as in Gallery View an item was listed at $20.00 and in List View it showed at $0.20

### PR DESCRIPTION
**Pull request by georgeteo**
On the can.

Fix #205

### CODE REVIEW

**Comment by fatlotus** [comment]
Might be good to add unit tests for this.

**Comment by georgeteo** [comment]
Add in this branch before merge?

**Comment by fatlotus** [comment]
Sure!

**Comment by fatlotus** [comment]
hehe @ "on the can"

**Comment by georgeteo** [comment]
Okie. Test looks good?

**Pull request merged**
