### PR TITLE
Serve the size requested in the template

### PR DESCRIPTION
**Pull request by fatlotus**
Currently, we serve the large size even if we're not meant to.

### CODE REVIEW

**Comment by georgeteo** [comment]
In line 46 of photos.py, why is the default size set to "original"? The SIZES dict only has "small" and "large" keys.

**Comment by fatlotus** [comment]
If a size is missing, it defaults to no resizing or cropping — hence "original." I'll add a comment to that effect.

**Comment by georgeteo** [comment]
Cool.

**Comment by fatlotus** [comment]
Ready to go?

**Pull request merged**
