### PR TITLE
Block API requests

### PR DESCRIPTION
**Pull request by fatlotus**
Emergency PR to temporarily block API requests from slowing down the service.

### CODE REVIEW

**Comment by georgeteo** [comment]
Is someone spamming api requests?

**Comment by fatlotus** [comment]
Yup :( It took out our quota on Tuesday. They're making a bunch of requests from EC2.

**Comment by fatlotus** [comment]
I had a janky version manually applied; this was just to get the master branch in sync.

**Comment by georgeteo** [comment]
okie.

**Pull request merged**
