### PR TITLE
Add secondary cache in front of NDB.

### PR DESCRIPTION
**Pull request by fatlotus**
To reduce the total number of reads, I thought we might try removing NDB entirely. I also added an endpoint [/_cache](https://reduce-reads-dot-caravel-code-reviews.appspot.com/_cache) that lets us poke the cache status.

https://reduce-reads-dot-caravel-code-reviews.appspot.com

### CODE REVIEW

**Comment by fatlotus** [comment]
Unclear if this helps :(

**Comment by georgeteo** [comment]
Did you update the app.yaml permissions?

**Comment by fatlotus** [comment]
Hm?

**Comment by fatlotus** [comment]
oh and bump

**Comment by georgeteo** [comment]
Should we allow everyone to view _cache? Or admin only?

**Comment by fatlotus** [comment]
Bump! Now it is admin-only.

**Comment by georgeteo** [comment]
Okie dokes.

**Pull request merged**
