### PR TITLE
Add affiliations field to new listings form

### PR DESCRIPTION
**Pull request by fatlotus**
Hi George, @tbkissinger,

This PR allows us to hide the button for people who cannot log in.

Remaining TODOs:
- [x] Add Affiliations field.
- [x] Replace home page login button with dropdown based on affiliation.
- [x] Make email/affiliation sticky

### CODE REVIEW

**Comment by fatlotus** [comment]
Boo ya! 

https://clean-authentication-dot-caravel-code-reviews.appspot.com/new

@tranv94 @tophatraptor @tbkissinger thoughts?

**Comment by tranv94** [comment]
Looks good, but just noticed the captcha at the bottom is a bit jumbled on mobile.

**Comment by tranv94** [comment]
Ignore my comment. It was on my end

**Comment by tophatraptor** [comment]
Captcha on the bottom also looked kind of jumbled on Chrome.

**Comment by georgeteo** [comment]
When refreshing/loading new listings page (https://clean-authentication-dot-caravel-code-reviews.appspot.com/new), there is a flicker when the green sign-in/enter email input field gets loaded before it gets hidden. 

Might be able to do something about the blank space in the header when not logged in, but that is not critical.

**Comment by georgeteo** [comment]
@tophatraptor I think thats cuz this is a test instance.

**Comment by fatlotus** [comment]
Thoughts on sign-in versus non-sign-in? What should the login button replacement look like?

**Comment by georgeteo** [comment]
Also, after I've signed in, the select your affiliation field isn't fixed to my affiliation. Might be good to have it autofill if you've signed in.

**Comment by georgeteo** [comment]
Re. thoughts on sign-in vs non-sign-in: I like the new version but might be good to get other people's opinion. 

Re. login button replacement: are you referring to the person figure at the top when you signed in? I think either that or a menu icon: 
screen shot 2016-05-07 at 2 46 31 pm

**Comment by fatlotus** [comment]
Oh! Sorry, meant the green person icon before the person signs in.

**Comment by georgeteo** [comment]
Isn't the green person gone in the new version? 
screen shot 2016-05-07 at 2 49 59 pm

**Comment by fatlotus** [comment]
Hrm, that's a good point. Right now it's only visible when the user has clicked the "Sign In" button on the New Listing form — which I could see being confusing. Should we remove it entirely?

Also, the affiliation is sticky only when we submit the form, so if they click the "Sign In" button, we lose all state. Lemme also fix that too.

**Comment by georgeteo** [comment]
Re. the man after sign in. I think having the menu is still important because accessing your own listings and "logging out" is probably a feature that people care about. The question is whether making it a different icon makes it clearer. I'd say yes, but other opinions are welcome. 

Also, I didn't actually test this, but is it sticky for non shibboleth people?

**Comment by fatlotus** [comment]
It's also not sticky for non-Shibboleth users :( Lemme see if I can add that too. My main worry is that people will see the menu once, then want to get it back later; hence why I think we might also need a "Log In" button.

**Comment by georgeteo** [comment]
I might not be following, but wasn't the point of this PR to get rid of the login button?

**Comment by fatlotus** [comment]
The biggest issue is that we dump non-Shibboleth users onto the Google Apps login page. While it'd be nice to get rid of the login feature, at least this way we get fewer support emails.

**Comment by fatlotus** [comment]
Bumpity bump. Thoughts overall?

**Comment by georgeteo** [comment]
After logging in, the select affiliation button is still not sticky. Oh but I guess we dont know which affiliation they are. Maybe remove it if logged in? 
screen shot 2016-05-10 at 8 50 42 pm

**Comment by georgeteo** [comment]
Also, really minor but "Alumni" instead of "Alum".

**Comment by fatlotus** [comment]
I think singular of alumni is "alumnus/alumnae/alum" — oh but wait, these are mixed singular/plural. Opinions on one versus the other?

**Comment by tranv94** [comment]
I'd go with Alumni since it's inclusive of both males and females.

Sidenote: Github doesn't recognize when I'm signed onto another github account and would just let me comment from there, despite clicking the link from this email. Weird.

**Comment by georgeteo** [comment]
I second @tranv94

**Comment by fatlotus** [comment]
I think alumnus/alumni/alumna/alumnae are the gendered versions, and alum is non-gendered? I never learned Latin, though, and Wikipedia is somewhat unhelpful.

**Comment by tranv94** [comment]
"If you're a male, you're an alumnus.  If there are a bunch of guys together, you're alumni.  If you're female, you're alumna.  A group of females is called alumnae.  However, if a group is made up of men and women, you're alumni again.  That is why you see "alumni" most often; it can be gender neutral."[0]

Also apparently alum isn't what we think it means.

http://www1.uwindsor.ca/alumni/alumnus-alumnae-alumni

**Comment by fatlotus** [comment]
Oh lordy, this is getting complicated.

Okay, last objection: it feels weird to describe myself (a singular person) as an "alumni." Maybe "former student"?

**Comment by tranv94** [comment]
Well let's be honest, if it's not accurate now someone will be eager to correct it. 

Maybe alumni is more prestigious? Kind of the title you earn once you graduate?

**Comment by georgeteo** [comment]
Re. Alum: Lets just pick one and go with it. I don't think it'll be too hard to change it if someone complains.

The bigger issue is non sticky dropdown after logging in. That might be confusing.

**Comment by fatlotus** [comment]
(Sorry, it'll be a few days — currently at ICPC in Thailand)

**Comment by georgeteo** [comment]
@fatlotus: no twitter/facebook commentary about ICPC?

**Comment by fatlotus** [comment]
Updated!

**Comment by georgeteo** [comment]
I think this problem has not been addressed?

After logging in, the select affiliation button is still not sticky. Oh but I guess we dont know which affiliation they are. Maybe remove it if logged in? 
f54a0fb2-16f0-11e6-96b4-7815fe1e2b23

**Comment by fatlotus** [comment]
Added stickiness for the home page login button. Thoughts?

**Comment by fatlotus** [comment]
(Bump, sorry — should've made that clear)

**Comment by georgeteo** [comment]
Looks good. Merge?

**Pull request merged**
