### PR TITLE
Add basic support for migration

### PR DESCRIPTION
**Pull request by fatlotus**
_so jetlagged :(_

I honestly haven't even tested this. I would advise against merging until I do; just thought I'd make adding the seller flag easier.

### CODE REVIEW

**Comment by georgeteo** [comment]
Will hold off on merging. 

Also not entirely sure about the distinction between replication and migration.

**Comment by fatlotus** [comment]
Apparently neither was I.

Replication is copying between services, migration is changing between versions. Better words?

**Comment by georgeteo** [comment]
Is still failing test.

**Comment by fatlotus** [comment]
Yeah- I'll take a look this evening — this is what I get for programming sleepy.

**Pull request merged**
