### PR TITLE
Add debug output to listing view

### PR DESCRIPTION
**Pull request by fatlotus**
Fairly rudimentary. I was using this on master... and it feels useful enough to keep long term. Thoughts? Are there other things that might be good to know?

By the way- it uses the existing App Engine users API — so as long as you're signed into Gmail with your App Engine admin account, it should show up. You can disable it for demos by adding ?external.

Test instance: er, prod hotfix, so master, but also https://add-handy-debug-view-dot-hosted-caravel.appspot.com.

Incidentally, all these test versions keep burning CPU time. It might be wise to create a separate App ID just for them...

### CODE REVIEW

**Comment by georgeteo** [comment]
Are any of my email admin for the Caravel appengine account? Is not appearing with either email.

**Comment by fatlotus** [comment]
hrm, me neither
clearly needs some work

**Comment by fatlotus** [comment]
Ah! You need to log in first. The jank way to do that is to go to (https://add-handy-debug-view-dot-hosted-caravel.appspot.com/_internal/login, just ignore the 404), then view any listing.

**Comment by georgeteo** [comment]
Cool beans. Good to merge?

**Comment by fatlotus** [comment]
I'm good. What are your thoughts?

**Comment by georgeteo** [comment]
I think is good. Will merge.

**Pull request merged**
